title:              Ayush Mahapatra
email:              ayushmahapatra97@gmail.com
description:        Website
author:             Ayush Mahapatra
baseurl:            ""
url:                "https://ayumahapat0.github.io"
theme:              spec.name

# Social Profiles
twitter_username:  
github_username:   ayumahapat0
facebook_username:  
instagram_username:  
linkedin_username: ayush-mahapatra-2a7420206

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site